name: Run map update on fly
on:
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Run map update
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: fly, fly, fly
          working-directory: ./fly/updater
          run: flyctl m run --verbose -a cmp-outage-map-generator-updater registry.fly.io/cmp-outage-map-generator-updater:amd64
        - name: how you doin?
          working-directory: ./fly/updater
          run: flyctl m list
